const clientCardBase: Card[] = [
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Diktatör",
    image: "dictator",
    cardDescription:
      "Altarnatif bir gerçeklikte karanlık tarafı ve yanlış olan tarafı seçtin",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "dictator",
    cardAttack: 4,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Gitarist",
    image: "guitar",
    cardDescription:
      "Seslerler çıkarıp düşmanı rahatsiz ediyorsun..'Ağğymm gonaswink from the şendıliir'",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "guitar",
    cardAttack: 3,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Ödenmiş Bedel",
    image: "soldier",
    cardDescription:
      "Bu kartı oynadıktan sonra iş bulma ihtimaliniz %50 artar.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "soldier",
    cardAttack: 1,
    cardHealth: 1,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Savaşçı",
    image: "worrior",
    cardDescription:
      "Savaşçı kartı oynandıktan sonra 3 zırh kazandırır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "worrior",
    cardAttack: 2,
    cardHealth: 9,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Askeri Harekat",
    image: "asker",
    cardDescription: "7.62 mm ile düşmana saldırır, her bir rakibin canını 1-3 azaltır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "asker",
    cardAttack: 4,
    cardHealth: 3,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Avci",
    image: "avci",
    cardDescription: "Usta bir iz sürücü, rakibine tuzak kurup ölümcül oklarıyla avlar.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "avci",
    cardAttack: 5,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Cat",
    image: "cat",
    cardDescription: "Çevik ve sessiz bir avcı. Kediye dönüşmüş, artık kendinde değil gibi görünüyor.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "cat",
    cardAttack: 1,
    cardHealth: 9,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Kolay Meslek",
    image: "dead",
    cardDescription: "Yattığın yerden para kazanırsın, aa ölmüşüm.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "dead",
    cardAttack: 1,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Dedektif",
    image: "dedektif",
    cardDescription: "Her hamlede ipucu toplayarak düşmanın zayıf noktalarını açığa çıkarır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "dedektif",
    cardAttack: 2,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Design",
    image: "design",
    cardDescription: "Bu kitabı okuduğunda, zihnine bilgi aktığını hissediyorsun.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "design",
    cardAttack: 2,
    cardHealth: 4,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Kyk",
    image: "kyk",
    cardDescription: "Görenlerin iştahını kaçırır, her bir düşmanın canını azaltır!",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "kyk",
    cardAttack: 3,
    cardHealth: 1,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Madenci",
    image: "madenci",
    cardDescription: "Derin kazılar yaparak hazine arar, patlayıcılarla engelleri aşar.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "madenci",
    cardAttack: 3,
    cardHealth: 4,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Rohan Atlısı",
    image: "parlamak",
    cardDescription: "Cesur Rohan atlısı, hız ve güçle düşmana saldırarak 5 zırh kazandırır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "parlamak",
    cardAttack: 5,
    cardHealth: 6,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "player",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "engin-pack",
    cardName: "Son Akşam Yemegi",
    image: "sonaksamyemegi",
    cardDescription: "Dostlarınızla yediğiniz şehirdeki son yemek, 3 zırh kazandırır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "sonaksamyemegi",
    cardAttack: 5,
    cardHealth: 3,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },

];

const enemyCardBase: Card[] = [
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Hacker Yavuz",
    image: "hacker",
    cardDescription: "Kardeşim az kaldı sızıyorum bölgeye. Bilgisayarını kapatırken bir şeyler yapmışım.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "hacker",
    cardAttack: 3,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Sleeper Coder",
    image: "sleeper",
    cardDescription: "Rüyasında bugları fixleyerek 5 hp yeniler",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "sleeper",
    cardAttack: 1,
    cardHealth: 1,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Atil Kedi",
    image: "atil_kedi",
    cardDescription: "Rakibe saldırır ve 1 can azaltır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "atil_kedi",
    cardAttack: 1,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Asker Yavuz",
    image: "asker",
    cardDescription: "Şiddetle ayağa kalkar. Kardeşim gece 2-4 nöbetim var rahatsız etme.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "asker",
    cardAttack: 5,
    cardHealth: 7,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Çay Zamanı",
    image: "cay",
    cardDescription: "Kısa bir çay molası verip, 2 hp yeniledikten sonra çatışmaya devam eder.",
    cardType: "spell",
    cardCost: 1,
    cardImageName: "cay",
    cardAttack: 3,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Deadline",
    image: "deadline",
    cardDescription: "Rakibe 3 can azaltır.",
    cardType: "spell",
    cardCost: 1,
    cardImageName: "deadline",
    cardAttack: 2,
    cardHealth: 1,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Arkadaşlar Çetesi",
    image: "friends",
    cardDescription: "Arkadaşlığın gücü adına! Bowling turnuvasına gider ve 5 zırh kazanır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "friends",
    cardAttack: 5,
    cardHealth: 5,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Hacker",
    image: "hacker",
    cardDescription: "Rakibe anında saldırarak 3 can azaltır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "hacker",
    cardAttack: 3,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Lahmacun Time",
    image: "lahmacun",
    cardDescription: "Düşmanın lahmacun dükkanına giderek en az 6(!) tane gömer, zırh olarak kullanır.",
    cardType: "spell",
    cardCost: 1,
    cardImageName: "lahmacun",
    cardAttack: 2,
    cardHealth: 3,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Ben Aslında Yoğum",
    image: "missing",
    cardDescription: "Yavuz zehirli düşman hasarlarından korunamk için kendini gizler.",
    cardType: "spell",
    cardCost: 1,
    cardImageName: "missing",
    cardAttack: 2,
    cardHealth: 5,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Bilboard Yavuz",
    image: "pano",
    cardDescription: "Düşman bölgesinde gizlice bilboardlara sızar, tüm düsmanlar şoka uğrar hepsinin 1 canı azalır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "pano",
    cardAttack: 2,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Radyasyon",
    image: "radyasyon",
    cardDescription: "Ukrayna Chernobyl bölgesinden iş teklifi gelir fakat gitmez, onlara bu fotoğrafı gönderir.",
    cardType: "spell",
    cardCost: 1,
    cardImageName: "radyasyon",
    cardAttack: 3,
    cardHealth: 3,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Roket Adam",
    image: "rocket",
    cardDescription: "Tasarladığı güdümlü roketler ile hedefin içinden geçer.",
    cardType: "spell",
    cardCost: 1,
    cardImageName: "rocket",
    cardAttack: 6,
    cardHealth: 2,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Super Yavuz",
    image: "superyavuz",
    cardDescription: "-O bir kuş!, - hayır o bir uçak, hayır o SÜPER YAVUZ",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "superyavuz",
    cardAttack: 7,
    cardHealth: 7,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  },
  {
    cardOwner: "enemy",
    profile: null,
    borderColor: null,
    isSelected: false,
    cardId: Math.random(),
    cardPack: "yavuz-pack",
    cardName: "Atıl Kedi",
    image: "tavan_kedi",
    cardDescription: "Yavuz'un tavan arasındaki kedis, aşağı inerek hepsinin 1 canını azaltır.",
    cardType: "minion",
    cardCost: 1,
    cardImageName: "tavan_kedi",
    cardAttack: 1,
    cardHealth: 9,
    cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
    deg: 0,
    move: 0,
    boardPairId: null
  }

];

export const getCardBaseLenght = ({
  player,
}: {
  player: "player" | "enemy";
}): number => {
  return player === "player" ? clientCardBase.length : enemyCardBase.length;
};

export const pullRandomCard = ({ isEnemy }: { isEnemy: boolean }) => {
  let randomIndex;
  let randomCard: any = null;
  if (isEnemy) {
    randomIndex = Math.floor(Math.random() * enemyCardBase.length);
    randomCard = enemyCardBase[randomIndex];
    enemyCardBase.splice(randomIndex, 1);
  } else {
    randomIndex = Math.floor(Math.random() * clientCardBase.length);
    randomCard = clientCardBase[randomIndex];
    clientCardBase.splice(randomIndex, 1);
  }

  return randomCard ? randomCard : null;
};
