import { Card } from "../types/Card.js";
export const characterPack: { [key: string]: Card[] } = {
  "jaina-pack": [
    {
      cardName: "Lamp Lighter",
      cardSkills: [{ type: "DealRandomEnemy", amount: 1 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "lamp_lighter",
      cardDescription: "When play this card, deal 1 damage to random enemy.",
      cardType: "minion",
      cardImageName: "lamp_lighter",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tripplewick Trickster",
      cardSkills: [{ type: "DealRandomEnemy", amount: 2 }],
      cardCost: 4,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "tripplewick_trickster",
      cardDescription: "When play this card, deal 2 damage to random enemy.",
      cardType: "minion",
      cardImageName: "tripplewick_trickster",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Saloon Brewmaster",
      cardSkills: [{ type: "ReturnToHandAndGiveHealth", amount: 2 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "saloon_brewmaster",
      cardDescription: "When play this, draw a card.",
      cardType: "minion",
      cardImageName: "saloon_brewmaster",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Flame Revenant",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 1 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "flame_revenant",
      cardDescription: "When play this, give random minion 1/1 attack/health.",
      cardType: "minion",
      cardImageName: "flame_revenant",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Spontaneous Combustion",
      cardSkills: [{ type: "DealRandomEnemy", amount: 4 }],
      cardCost: 2,
      cardAttack: 0,
      cardHealth: 0,
      image: "spontaneous_combustion",
      cardImageName: "spontaneous_combustion",
      cardDescription: "When play this, give 4 damage to random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Solar Flare",
      cardSkills: [{ type: "DealRandomEnemy", amount: 4 }],
      cardCost: 5,
      cardAttack: 0,
      cardHealth: 0,
      image: "solar_flare",
      cardImageName: "solar_flare",
      cardDescription: "When play this, give 4 damage to random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tidepool Pupil",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      image: "tidepool_pupil",
      cardImageName: "tidepool_pupil",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Redgill Razorjaw",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 2,
      image: "redgill_razorjaw",
      cardImageName: "redgill_razorjaw",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Unchained Gladiator",
      cardSkills: [],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 4,
      image: "unchained_gladiator",
      cardImageName: "unchained_gladiator",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Raid Leader",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "raid_leader",
      cardImageName: "raid_leader",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Gorgonzormu",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 3,
      image: "gorgonzormu",
      cardImageName: "gorgonzormu",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Shield Master",
      cardSkills: [{ type: "GainArmor", amount: 4 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "shield_master",
      cardImageName: "shield_master",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "boulderfist_ogre",
      cardImageName: "boulderfist_ogre",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "dread_corsair",
      cardImageName: "dread_corsair",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Lamp Lighter",
      cardSkills: [{ type: "DealRandomEnemy", amount: 1 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "lamp_lighter",
      cardDescription: "When play this card, deal 1 damage to random enemy.",
      cardType: "minion",
      cardImageName: "lamp_lighter",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tripplewick Trickster",
      cardSkills: [{ type: "DealRandomEnemy", amount: 2 }],
      cardCost: 4,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "tripplewick_trickster",
      cardDescription: "When play this card, deal 2 damage to random enemy.",
      cardType: "minion",
      cardImageName: "tripplewick_trickster",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Saloon Brewmaster",
      cardSkills: [{ type: "ReturnToHandAndGiveHealth", amount: 2 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "saloon_brewmaster",
      cardDescription: "When play this, draw a card.",
      cardType: "minion",
      cardImageName: "saloon_brewmaster",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Flame Revenant",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 1 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      image: "flame_revenant",
      cardDescription: "When play this, give random minion 1/1 attack/health.",
      cardType: "minion",
      cardImageName: "flame_revenant",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Spontaneous Combustion",
      cardSkills: [{ type: "DealRandomEnemy", amount: 4 }],
      cardCost: 2,
      cardAttack: 0,
      cardHealth: 0,
      image: "spontaneous_combustion",
      cardImageName: "spontaneous_combustion",
      cardDescription: "When play this, give 4 damage to random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Solar Flare",
      cardSkills: [{ type: "DealAllEnemy", amount: 2 }],
      cardCost: 5,
      cardAttack: 0,
      cardHealth: 0,
      image: "solar_flare",
      cardImageName: "solar_flare",
      cardDescription: "When play this, deal 2 damage  to all enemies.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tidepool Pupil",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      image: "tidepool_pupil",
      cardImageName: "tidepool_pupil",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Redgill Razorjaw",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 2,
      image: "redgill_razorjaw",
      cardImageName: "redgill_razorjaw",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Unchained Gladiator",
      cardSkills: [],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 4,
      image: "unchained_gladiator",
      cardImageName: "unchained_gladiator",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Raid Leader",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "raid_leader",
      cardImageName: "raid_leader",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Gorgonzormu",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 3,
      image: "gorgonzormu",
      cardImageName: "gorgonzormu",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Shield Master",
      cardSkills: [{ type: "GainArmor", amount: 4 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "shield_master",
      cardImageName: "shield_master",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "boulderfist_ogre",
      cardImageName: "boulderfist_ogre",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "dread_corsair",
      cardImageName: "dread_corsair",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
  ],
  "engin-pack": [
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "jaina-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Diktatör",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 3 }],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 2,
      image: "dictator",
      cardImageName: "dictator",
      cardDescription:
        "Altarnatif bir gerçeklikte karanlık tarafı ve yanlış olan tarafı seçtin",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Gitarist",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 3,
      cardHealth: 2,
      image: "guitar",
      cardImageName: "guitar",
      cardDescription:
        "Seslerler çıkarıp düşmanı rahatsiz ediyorsun..'Ağğymm gonaswink from the şendıliir'",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Ödenmiş Bedel",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 1,
      image: "soldier",
      cardImageName: "soldier",
      cardDescription:
        "Bu kartı oynadıktan sonra iş bulma ihtimaliniz %50 artar.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Savaşçı",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 9,
      image: "worrior",
      cardImageName: "worrior",
      cardDescription: "Savaşçı kartı oynandıktan sonra 3 zırh kazandırır.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Askeri Harekat",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 4,
      cardHealth: 3,
      image: "asker",
      cardImageName: "asker",
      cardDescription:
        "7.62 mm ile düşmana saldırır, her bir rakibin canını 1-3 azaltır.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Avci",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 2,
      image: "avci",
      cardImageName: "avci",
      cardDescription:
        "Usta bir iz sürücü, rakibine tuzak kurup ölümcül oklarıyla avlar.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Cat",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 9,
      image: "cat",
      cardImageName: "cat",
      cardDescription:
        "Çevik ve sessiz bir avcı. Kediye dönüşmüş, artık kendinde değil gibi görünüyor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kolay Meslek",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 2,
      image: "dead",
      cardImageName: "dead",
      cardDescription: "Yattığın yerden para kazanırsın, aa ölmüşüm.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Dedektif",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 2,
      image: "dedektif",
      cardImageName: "dedektif",
      cardDescription:
        "Her hamlede ipucu toplayarak düşmanın zayıf noktalarını açığa çıkarır.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Design",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 4,
      image: "design",
      cardImageName: "design",
      cardDescription:
        "Bu kitabı okuduğunda, zihnine bilgi aktığını hissediyorsun.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kyk",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 3,
      cardHealth: 1,
      image: "kyk",
      cardImageName: "kyk",
      cardDescription:
        "Görenlerin iştahını kaçırır, her bir düşmanın canını azaltır!",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Madenci",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 3,
      cardHealth: 4,
      image: "madenci",
      cardImageName: "madenci",
      cardDescription:
        "Derin kazılar yaparak hazine arar, patlayıcılarla engelleri aşar.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Rohan Atlısı",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 5,
      cardHealth: 6,
      image: "parlamak",
      cardImageName: "parlamak",
      cardDescription:
        "Cesur Rohan atlısı, hız ve güçle düşmana saldırarak 5 zırh kazandırır.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Son Akşam Yemegi",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 5,
      cardHealth: 3,
      image: "sonaksamyemegi",
      cardImageName: "sonaksamyemegi",
      cardDescription:
        "Dostlarınızla yediğiniz şehirdeki son yemek, 3 zırh kazandırır.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "engin-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
  ],
  "yavuz-pack": [
    {
      cardName: "Pisko Çakaya",
      cardSkills: [{ type: "ReturnToHandAndGiveHealth", amount: 3 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 2,
      image: "hacker",
      cardImageName: "hacker",
      cardDescription:
        "Kullanıcının antivirüsü çekirdek çitlerken, içeri sızar. Rasgele bir dost kartı yok eder ve 3/3 attack/health güçlendirerek ele geri verir.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "DayDreamer",
      cardSkills: [{ type: "HealCard", amount: 2 }],
      cardCost: 5,
      cardAttack: 1,
      cardHealth: 10,
      image: "sleeper",
      cardImageName: "sleeper",
      cardDescription:
        "Hayalinde bugları fixleyerek müttefik bir karta 2 can verir.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Atil Kedi",
      cardSkills: [{ type: "DealRandomEnemy", amount: 3 }],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 1,
      image: "atil_kedi",
      cardImageName: "atil_kedi",
      cardDescription: "Rasgele bir düşmana atlar ve 3 can azaltır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Bordo Bedelli",
      cardSkills: [{ type: "HealHero", amount: 5 }],
      cardCost: 5,
      cardAttack: 5,
      cardHealth: 7,
      image: "asker",
      cardImageName: "asker",
      cardDescription: "Şiddetle ayağa kalkar, sahibine 5 can verir.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Çay Zamanı",
      cardSkills: [{ type: "HealHero", amount: 2 }],
      cardCost: 2,
      cardAttack: 1,
      cardHealth: 4,
      image: "cay",
      cardImageName: "cay",
      cardDescription:
        "İnce belli bardağı hüpletip sahibine 2 can verir ve çatışmaya devam eder.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Deadline",
      cardSkills: [{ type: "DealAllEnemy", amount: 2 }],
      cardCost: 3,
      cardAttack: 6,
      cardHealth: 1,
      image: "deadline",
      cardImageName: "deadline",
      cardDescription: "Tüm düşmanların canını 2 azaltır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Arkadaşlar Çetesi",
      cardSkills: [{ type: "GainArmor", amount: 5 }],
      cardCost: 5,
      cardAttack: 1,
      cardHealth: 10,
      image: "friends",
      cardImageName: "friends",
      cardDescription:
        "Arkadaşlığın gücü adına! Bowling turnuvasına gider ve 5 zırh kazanır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kaspersky Yavuz",
      cardSkills: [{ type: "DealRandomEnemy", amount: 3 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 2,
      image: "hacker",
      cardImageName: "hacker",
      cardDescription:
        "Rasgele bir düşmanın virüs programına at sesi çıkartarak korkutup, 3 can azaltır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Lavacun Time",
      cardSkills: [{ type: "GainArmor", amount: 6 }],
      cardCost: 5,
      cardAttack: 3,
      cardHealth: 2,
      image: "lahmacun",
      cardImageName: "lahmacun",
      cardDescription:
        "Düşmanın lahmacun dükkanına giderek en az 6(!) tane gömer, zırh olarak kullanır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Ben Aslında Yoğum",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 2,
      image: "missing",
      cardImageName: "missing",
      cardDescription: "Kendini gizlemek için elinden geleni yapar.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Bilboard Yavuz",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 1,
      image: "pano",
      cardImageName: "pano",
      cardDescription: "",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Radyasyon",
      cardSkills: [{ type: "DrawCard" }],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 1,
      image: "radyasyon",
      cardImageName: "radyasyon",
      cardDescription:
        "Ukrayna Chernobyl bölgesinden iş teklifi gelir fakat gitmez, 1 kart çeker ve onlara gönderir.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kim-Jong Yavuz",
      cardSkills: [{ type: "DealRandomEnemy", amount: 3 }, { type: "GainArmor", amount: 2 }],
      cardCost: 5,
      cardAttack: 4,
      cardHealth: 4,
      image: "rocket",
      cardImageName: "rocket",
      cardDescription:
        "Kuzey Kore lideri Kim Jong Un'un gizli kardeşi, füze atarak rasgele bir düşmana 3 can azaltır ve 2 zırh kazanır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "spell",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Bızdıkmen Yavuz",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 2,
      image: "superyavuz",
      cardImageName: "superyavuz",
      cardDescription: "-O bir kuş!, -hayır bir uçak, hayır o BIZDIKMEN",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kedi Özel Harekat",
      cardSkills: [{ type: "HealRandomCard", amount: 2 }],
      cardCost: 2,
      cardAttack: 0,
      cardHealth: 4,
      image: "tavan_kedi",
      cardImageName: "tavan_kedi",
      cardDescription:
        "İşte geliyor özel hareCAT şarkısı eşliğinde, rasgele bir dostun canını 2 arttırır.",
      cardOwner: "enemy",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "yavuz-pack",
      cardType: "minion",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
  ],
  "mustafa-pack": [
    {
      cardName: "Gece Parıltısı",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 2 }],
      cardCost: 3,
      cardAttack: 0,
      cardHealth: 0,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "moon",
      cardDescription:
        "Gökyüzünün derinliklerinde ışıldayan Gece Parıltısı, masadaki kartları güçlendirerek dengeleri değiştirebilir. Ay ışığının sihriyle, rakiplerini şaşırtırken rastgele bir kartı güçlendirir.",
      cardType: "spell",
      cardImageName: "moon",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Uzay Yolcusu Zeki",
      cardSkills: [{ type: "HealAllCards", amount: 1 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "astronaut_zeki_muren",
      cardDescription:
        "Uzayın derinliklerinden gelen bu kart, tüm dost birimlere +1 can kazandırır.",
      cardType: "minion",
      cardImageName: "astronaut_zeki_muren",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Engel Düşmanı Tosbik",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "climbing_turtle",
      cardDescription:
        "",
      cardType: "minion",
      cardImageName: "climbing_turtle",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Adaletin Adamı",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "better_call_saul_jimmy",
      cardDescription:
        "",
      cardType: "minion",
      cardImageName: "better_call_saul_jimmy",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Cezalandırıcı",
      cardSkills: [{ type: "DealAll", amount: 1 }],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "punisher",
      cardDescription:
        "Savaşa adanmış ruhuyla ve dikkatsizliğiyle oyundaki herkesi cezalandırarak 1 hasar verir.",
      cardType: "minion",
      cardImageName: "punisher",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Ayaklı Gizem",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "standing_cat",
      cardDescription:
        "Bu kedicik bir sır saklıyor. Sanırım biraz daha gizemli kalacak.",
      cardType: "minion",
      cardImageName: "standing_cat",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Büyük Çığlık",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "big_scream_cat",
      cardDescription:
        "",
      cardType: "minion",
      cardImageName: "big_scream_cat",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Anı Yakala",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 0,
      cardHealth: 0,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "photo_selfie",
      cardDescription:
        "",
      cardType: "spell",
      cardImageName: "photo_selfie",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Deniz Arayıcısı",
      cardSkills: [{ type: "HealHero", amount: 1 }],
      cardCost: 3,
      cardAttack: 2,
      cardHealth: 4,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "fishing",
      cardDescription:
        "Denizle bütünleşmiş bu karakter, suların saklı gücünü kahramana hediye eder, 5 can kazandırır.",
      cardType: "minion",
      cardImageName: "fishing",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kafes Kralı Maviş",
      cardSkills: [{ type: "DealRandomEnemy", amount: 3 }],
      cardCost: 2,
      cardAttack: 1,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "caged_bird",
      cardDescription:
        "Küçük ama güçlü; her kuşun bir kral olabileceğini gösterir. Hızlı bir saldırı ile rastgele bir düşmana 4 hasar verir",
      cardType: "minion",
      cardImageName: "caged_bird",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Aqua Man",
      cardSkills: [],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "aqua_selfie",
      cardDescription:
        "",
      cardType: "minion",
      cardImageName: "aqua_selfie",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Sadık Dost",
      cardSkills: [{ type: "HealAllCards", amount: 1 }],
      cardCost: 3,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "dog_view",
      cardDescription:
        "Manzarada bulduğu huzur, yanındaki dostları da besler. Sadık dost, her cana değer katar. Masadaki tüm dostların canını 1 arttırır.",
      cardType: "minion",
      cardImageName: "dog_view",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Öğrenilmiş Çaresizlik",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 0,
      cardHealth: 0,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "thief",
      cardDescription:
        "",
      cardType: "spell",
      cardImageName: "thief",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Bulmaca Ustası",
      cardSkills: [{ type: "ReturnToHandAndGiveHealth", amount: 3 }],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "puzzle_turtle",
      cardDescription:
        "Bulmacanın büyüsüyle bir kartı yok eder, eline 3/3 attack/health güçlendirerek ele geri verir. ",
      cardType: "minion",
      cardImageName: "puzzle_turtle",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Rüzgar Sürücüsü",
      cardSkills: [],
      cardCost: 4,
      cardAttack: 3,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "mustafa-pack",
      image: "biker_selfie",
      cardDescription:
        "Yolun rüzgarını arkasına alarak süratle yolculuğa çıkan bir özgür ruh.",
      cardType: "minion",
      cardImageName: "biker_selfie",
      cardPosition: { x: 0, y: 0, top: 0, size: 150, offset: 0 },
      deg: 0,
      move: 0,
      boardPairId: null,
    },
  ],
};
